=== Tyjow/Challenge_3/Cv.dtd
<!ELEMENT Cv (Personne, experience*, formation*, competence*, divers)>
<!ELEMENT Personne (image?, nom, prenom, age, date_de_naissance, adresse, telephone, mail, permis?)>
<!ATTLIST Personne sexe (masculin|feminin) "masculin">
<!ELEMENT image EMPTY>
<!ATTLIST image source CDATA #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT date_de_naissance (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT permis (#PCDATA)>
<!ELEMENT experience (date, poste*)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT poste (entreprise, lieu, descriptif)>
<!ELEMENT entreprise (#PCDATA)>
<!ELEMENT lieu (#PCDATA)>
<!ELEMENT descriptif (#PCDATA)>
<!ELEMENT formation (date, intitule, organisme, lieu, niveau)>
<!ELEMENT intitule (#PCDATA)>
<!ELEMENT organisme (#PCDATA)>
<!ELEMENT niveau (#PCDATA)>
<!ELEMENT competence (langage*, niveau)>
<!ELEMENT langage (#PCDATA)>
<!ELEMENT divers (langue*, loisirs*)>
<!ELEMENT langue (#PCDATA)>
<!ELEMENT loisirs (#PCDATA)>

=== Tyjow/Challenge_3/Cv.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE Cv SYSTEM "Cv.dtd">

<Cv>
<Personne sexe="masculin">
	<image source="Images/photo.jpg"></image>
	<nom></nom>
	<prenom></prenom>
	<age></age>
	<date_de_naissance></date_de_naissance>
	<adresse></adresse>
	<telephone></telephone>
	<mail></mail>
	<permis></permis>
</Personne>

<experience>
	<date></date>
	<poste>
		<entreprise></entreprise>
		<lieu></lieu>
		<descriptif></descriptif>
	</poste>
</experience>

<formation>
	<date></date>
	<intitule></intitule>
	<organisme></organisme>
	<lieu></lieu>
	<niveau></niveau>
</formation>

<competence>
	<langage></langage>
	<niveau></niveau>
</competence>

</Cv>
